services:
  influx-db:
    build:
      context: influx-db
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=plantdatabase
      - INFLUXDB_ADMIN_USER=plant
      - INFLUXDB_ADMIN_PASSWORD=data
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    restart: unless-stopped

  grafana:
    build:
      context: grafana
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_EXPLORE_ENABLED=false
      - GF_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_FEATURE_TOGGLES_DATACONNECTIONSCONSOLE=false
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_INSTALL_PLUGINS=volkovlabs-variable-panel, williamvenner-timepickerbuttons-panel, speakyourcode-button-panel
      # - GF_SECURITY_ADMIN_USER=${USER} #super user login
      # - GF_SECURITY_ADMIN_PASSWORD=${PASS}
      - GF_PANELS_DISABLE_SANITIZE_HTML=true #allows scripting in text panels
    ports:
     - 3010:3000
    volumes:
      - grafana-data:/var/lib/grafana
      # - ./provisioning:/etc/grafana/provisioning:rw
    restart: unless-stopped

volumes:
  influxdb_data:
  grafana-data: