{
 "title": "Live Plant Data",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "device_id",
    "label": "Sensor ID",
    "query": "Pothos : 0,Tomato Plant : 1, 2, 3, 4"
   },
   { "name": "domain", "query": "0" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 1, "y": 0 }, "options": { "content": "#  Live Plant Dashboard" } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 0 },
   "options": {
    "content": "To update the name of a sensor go to the settings gear -> variables and edit the names without modifying the numbers."
   }
  },
  { "title": "${device_id}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }, "repeat": "device_id" },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"iot_sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plant_monitors\")\n  |> filter(fn: (r) => r[\"SSID\"] == \"The House That Eggs Together\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"device\"] == \"${device_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 20)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "targets": [
    { "expression": "($A * 9/5) + 32", "type": "math" }
   ]
  },
  {
   "title": "Wetness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"iot_sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plant_monitors\")\n  |> filter(fn: (r) => r[\"SSID\"] == \"The House That Eggs Together\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wetness\")\n  |> filter(fn: (r) => r[\"device\"] == \"${device_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 100)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}