{
 "title": "Sensor Data Page",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "device_id", "label": "Sensor ID", "query": "Tomato Plant : 1, 2" },
   { "name": "domain", "query": "0" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 19, "x": 1, "y": 0 }, "options": { "content": "#  Dashboard for ${device_id}" } },
  { "title": "Home page", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 21, "y": 0 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"iot_sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plant_monitors\")\n  |> filter(fn: (r) => r[\"SSID\"] == \"The House That Eggs Together\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"device\"] == \"${device_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"iot_sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plant_monitors\")\n  |> filter(fn: (r) => r[\"SSID\"] == \"The House That Eggs Together\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"device\"] == \"${device_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wifi Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"iot_sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plant_monitors\")\n  |> filter(fn: (r) => r[\"SSID\"] == \"The House That Eggs Together\")\n  |> filter(fn: (r) => r[\"_field\"] == \"signal_strength\")\n  |> filter(fn: (r) => r[\"device\"] == \"${device_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wetness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"iot_sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plant_monitors\")\n  |> filter(fn: (r) => r[\"SSID\"] == \"The House That Eggs Together\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wetness\")\n  |> filter(fn: (r) => r[\"device\"] == \"${device_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}